import { MigrationInterface, QueryRunner } from "typeorm";

export class FakePosts1608177460897 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        insert into post (title, text, "creatorId") values ('Fairhaven', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1);
insert into post (title, text, "creatorId") values ('Nenette and Boni (Nénette et Boni)', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into post (title, text, "creatorId") values ('The Final Girl', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into post (title, text, "creatorId") values ('Chronicle of My Mother (Waga haha no ki)', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1);
insert into post (title, text, "creatorId") values ('Austin Powers in Goldmember', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1);
insert into post (title, text, "creatorId") values ('Duchess, The', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1);
insert into post (title, text, "creatorId") values ('When Pigs Have Wings', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1);
insert into post (title, text, "creatorId") values ('No Greater Love', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1);
insert into post (title, text, "creatorId") values ('Hector and the Search for Happiness', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1);
insert into post (title, text, "creatorId") values ('Stephanie Daley', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1);
insert into post (title, text, "creatorId") values ('Last Days on Mars, The', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1);
insert into post (title, text, "creatorId") values ('Dream (Bi-mong)', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1);
insert into post (title, text, "creatorId") values ('Rainmaker, The', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1);
insert into post (title, text, "creatorId") values ('Orgazmo', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1);
insert into post (title, text, "creatorId") values ('Step Up', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into post (title, text, "creatorId") values ('Midnight Chronicles', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1);
insert into post (title, text, "creatorId") values ('Outlaw, The (Lope)', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1);
insert into post (title, text, "creatorId") values ('Headquarters (Päämaja) ', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into post (title, text, "creatorId") values ('Love That Boy', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1);
insert into post (title, text, "creatorId") values ('Laughing Woman, The (Frightened Woman, The) (Femina ridens)', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1);
insert into post (title, text, "creatorId") values ('Bloodsport 2 (a.k.a. Bloodsport II: The Next Kumite)', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1);
insert into post (title, text, "creatorId") values ('Fresh Horses', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1);
insert into post (title, text, "creatorId") values ('River Wild, The', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1);
insert into post (title, text, "creatorId") values ('Trigun: Badlands Rumble', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1);
insert into post (title, text, "creatorId") values ('Porn Theater (Chatte à deux têtes, La)', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1);
insert into post (title, text, "creatorId") values ('Satyricon', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1);
insert into post (title, text, "creatorId") values ('Another You', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1);
insert into post (title, text, "creatorId") values ('Kolberg', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1);
insert into post (title, text, "creatorId") values ('Report to the Commissioner', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into post (title, text, "creatorId") values ('Otaku', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1);
insert into post (title, text, "creatorId") values ('Experience, The (Tadjrebeh)', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1);
insert into post (title, text, "creatorId") values ('Boy Culture', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1);
insert into post (title, text, "creatorId") values ('Lullaby', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into post (title, text, "creatorId") values ('So It Goes (Korsoteoria)', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1);
insert into post (title, text, "creatorId") values ('E.T. the Extra-Terrestrial', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1);
insert into post (title, text, "creatorId") values ('For the Birds', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1);
insert into post (title, text, "creatorId") values ('3 Worlds of Gulliver, The', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1);
insert into post (title, text, "creatorId") values ('Man with the Movie Camera, The (Chelovek s kino-apparatom)', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1);
insert into post (title, text, "creatorId") values ('Babysitter Wanted', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1);
insert into post (title, text, "creatorId") values ('Dead Man Down', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into post (title, text, "creatorId") values ('Sherlock Holmes: Terror by Night', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1);
insert into post (title, text, "creatorId") values ('Meet Monica Velour', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1);
insert into post (title, text, "creatorId") values ('Poison Ivy II', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1);
insert into post (title, text, "creatorId") values ('Expect No Mercy', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1);
insert into post (title, text, "creatorId") values ('Last Shot, The', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1);
insert into post (title, text, "creatorId") values ('Dark Dungeons', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1);
insert into post (title, text, "creatorId") values ('Run All Night', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1);
insert into post (title, text, "creatorId") values ('Magnificent Ambersons, The', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1);
insert into post (title, text, "creatorId") values ('Monsterman (Monsterimies)', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1);
insert into post (title, text, "creatorId") values ('Familie, En', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1);
insert into post (title, text, "creatorId") values ('No Blood Relation (Stepchild, The) (Nasanunaka)', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1);
insert into post (title, text, "creatorId") values ('Things We Lost in the Fire', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1);
insert into post (title, text, "creatorId") values ('Demolition Man', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1);
insert into post (title, text, "creatorId") values ('Main Street', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1);
insert into post (title, text, "creatorId") values ('Smart Money', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1);
insert into post (title, text, "creatorId") values ('Babes in Toyland', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into post (title, text, "creatorId") values ('Kinjite: Forbidden Subjects', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into post (title, text, "creatorId") values ('Earthsea (Legend of Earthsea)', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1);
insert into post (title, text, "creatorId") values ('Adventures of the Wilderness Family, The', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1);
insert into post (title, text, "creatorId") values ('Silence of the Lambs, The', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into post (title, text, "creatorId") values ('Wake of the Red Witch', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1);
insert into post (title, text, "creatorId") values ('Dakota', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1);
insert into post (title, text, "creatorId") values ('Agronomist, The', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1);
insert into post (title, text, "creatorId") values ('Gun Fury', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1);
insert into post (title, text, "creatorId") values ('A.C.O.D.', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1);
insert into post (title, text, "creatorId") values ('Wishmaster', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1);
insert into post (title, text, "creatorId") values ('National Security', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1);
insert into post (title, text, "creatorId") values ('India''s Daughter', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1);
insert into post (title, text, "creatorId") values ('Death Wish 5: The Face of Death', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1);
insert into post (title, text, "creatorId") values ('Klitschko', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1);
insert into post (title, text, "creatorId") values ('18 Years Later (Diciotto anni dopo)', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1);
insert into post (title, text, "creatorId") values ('Interview with a Hitman', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1);
insert into post (title, text, "creatorId") values ('Red Chapel (Røde kapel)', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1);
insert into post (title, text, "creatorId") values ('Taste of Cherry (Ta''m e guilass)', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1);
insert into post (title, text, "creatorId") values ('If I Stay', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1);
insert into post (title, text, "creatorId") values ('Invitation to a Gunfighter', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1);
insert into post (title, text, "creatorId") values ('Performance', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1);
insert into post (title, text, "creatorId") values ('Bowfinger', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1);
insert into post (title, text, "creatorId") values ('Just Imagine', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1);
insert into post (title, text, "creatorId") values ('Bloody Birthday', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1);
insert into post (title, text, "creatorId") values ('Sarah Silverman: Jesus Is Magic', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1);
insert into post (title, text, "creatorId") values ('Great Happiness Space, The: Tale of an Osaka Love Thief', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1);
insert into post (title, text, "creatorId") values ('Park Avenue: Money, Power and the American Dream', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into post (title, text, "creatorId") values ('Lesser Blessed, The', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into post (title, text, "creatorId") values ('Splinter', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1);
insert into post (title, text, "creatorId") values ('Vampire, The', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1);
insert into post (title, text, "creatorId") values ('Tell', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1);
insert into post (title, text, "creatorId") values ('Gorgeous Hussy, The', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1);
insert into post (title, text, "creatorId") values ('Samaritan Girl (Samaria)', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into post (title, text, "creatorId") values ('For All Mankind', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1);
insert into post (title, text, "creatorId") values ('Letters to Juliet', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1);
insert into post (title, text, "creatorId") values ('Venus Beauty Institute (Vénus beauté)', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1);
insert into post (title, text, "creatorId") values ('Yesterday', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1);
insert into post (title, text, "creatorId") values ('Hammer of the Gods', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1);
insert into post (title, text, "creatorId") values ('Fraulein (Das Fräulein) ', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1);
insert into post (title, text, "creatorId") values ('My Ain Folk', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1);
insert into post (title, text, "creatorId") values ('Pretty Maids All in a Row', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1);
insert into post (title, text, "creatorId") values ('The great match', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1);
insert into post (title, text, "creatorId") values ('I Really Hate My Job', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1);
insert into post (title, text, "creatorId") values ('Light of Day', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1);
        `);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
